apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.nfs.name }}"
spec:
  capacity:
    storage: "{{ .Values.nfs.capacity }}"
  accessModes:
    - ReadWriteMany
  nfs:
    server: "{{ .Values.nfs.clusterIP }}"
    path: "{{ .Values.nfs.path }}"
